sudo rm /var/log/nginx/sfg500/1/access.log
sudo rm /var/log/nginx/sfg500/2/access.log
sudo rm /var/log/nginx/sfg500/3/access.log
sudo rm /var/log/nginx/sfg500/4/access.log
sudo rm /var/log/nginx/sfg500/5/access.log
sudo rm /var/log/nginx/sfg500/6/access.log
sudo rm /var/log/nginx/sfg500/7/access.log
sudo rm /var/log/nginx/sfg500/8/access.log
sudo rm /var/log/nginx/sfg500/9/access.log
sudo rm /var/log/nginx/sfg500/10/access.log
