version: '3'

services:
  sfg500-01:
    image: nginx
    container_name: sfg500-01
    hostname: pi-bas0002-sfg500-01
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.200.1.101
    volumes:
      - /var/log/nginx/sfg500/1:/var/log/nginx
      - /usr/share/nginx/html/sfg500/1:/usr/share/nginx/html:ro

  sfg500-02:
    image: nginx
    container_name: sfg500-02
    hostname: pi-bas0002-sfg500-02
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.200.1.102
    volumes:
      - /var/log/nginx/sfg500/2:/var/log/nginx
      - /usr/share/nginx/html/sfg500/2:/usr/share/nginx/html:ro

  sfg500-03:
    image: nginx
    container_name: sfg500-03
    hostname: pi-bas0002-sfg500-03
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.200.1.103
    volumes:
      - /var/log/nginx/sfg500/3:/var/log/nginx
      - /usr/share/nginx/html/sfg500/3:/usr/share/nginx/html:ro

  sfg500-04:
    image: nginx
    container_name: sfg500-04
    hostname: pi-bas0002-sfg500-04
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.200.1.104
    volumes:
      - /var/log/nginx/sfg500/4:/var/log/nginx
      - /usr/share/nginx/html/sfg500/4:/usr/share/nginx/html:ro

  sfg500-05:
    image: nginx
    container_name: sfg500-05
    hostname: pi-bas0002-sfg500-05
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.200.1.105
    volumes:
      - /var/log/nginx/sfg500/5:/var/log/nginx
      - /usr/share/nginx/html/sfg500/5:/usr/share/nginx/html:ro

  sfg500-06:
    image: nginx
    container_name: sfg500-06
    hostname: pi-bas0002-sfg500-06
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.200.1.106
    volumes:
      - /var/log/nginx/sfg500/6:/var/log/nginx
      - /usr/share/nginx/html/sfg500/6:/usr/share/nginx/html:ro

  sfg500-07:
    image: nginx
    container_name: sfg500-07
    hostname: pi-bas0002-sfg500-07
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.200.1.107
    volumes:
      - /var/log/nginx/sfg500/7:/var/log/nginx
      - /usr/share/nginx/html/sfg500/7:/usr/share/nginx/html:ro

  sfg500-08:
    image: nginx
    container_name: sfg500-08
    hostname: pi-bas0002-sfg500-08
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.200.1.108
    volumes:
      - /var/log/nginx/sfg500/8:/var/log/nginx
      - /usr/share/nginx/html/sfg500/8:/usr/share/nginx/html:ro

  sfg500-09:
    image: nginx
    container_name: sfg500-09
    hostname: pi-bas0002-sfg500-09
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.200.1.109
    volumes:
      - /var/log/nginx/sfg500/9:/var/log/nginx
      - /usr/share/nginx/html/sfg500/9:/usr/share/nginx/html:ro

  sfg500-10:
    image: nginx
    container_name: sfg500-10
    hostname: pi-bas0002-sfg500-10
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.200.1.110
    volumes:
      - /var/log/nginx/sfg500/10:/var/log/nginx
      - /usr/share/nginx/html/sfg500/10:/usr/share/nginx/html:ro
      
networks:
  default:
    external:
      name: macvlan200
